Workflow file for this run
.github/workflows/void-build.yml at 9e177c7
name: Build Void

on:
  push:
    branches: [ main, release/*, github-workflow ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev
          # Set npm config to use GitHub token for authentication to avoid rate limits
          npm config set //github.com/:_authToken=${{ github.token }}
          npm config set //api.github.com/:_authToken=${{ github.token }}
          npm config set //npm.pkg.github.com/:_authToken=${{ github.token }}
          # Configure npm to use the GitHub token for all requests to github.com domains
          npm config set @microsoft:registry https://npm.pkg.github.com
          npm config set @vscode:registry https://npm.pkg.github.com
          # Increase network timeout to handle slow connections
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        run: |
          npm run buildreact
          npm run gulp vscode-linux-x64-min
      - name: Package
        run: |
          mkdir -p .build/linux/client
          ARCHIVE_PATH=".build/linux/client/void-linux-x64.tar.gz"
          tar -czf $ARCHIVE_PATH -C .. VSCode-linux-x64
      - name: Generate checksum
        run: |
          cd .build/linux/client
          sha256sum void-linux-x64.tar.gz > void-linux-x64.tar.gz.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: void-linux-x64
          path: |
            .build/linux/client/void-linux-x64.tar.gz
            .build/linux/client/void-linux-x64.tar.gz.sha256
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev
          # Set npm config to use GitHub token for authentication to avoid rate limits
          npm config set //github.com/:_authToken=${{ github.token }}
          npm config set //api.github.com/:_authToken=${{ github.token }}
          npm config set //npm.pkg.github.com/:_authToken=${{ github.token }}
          # Configure npm to use the GitHub token for all requests to github.com domains
          npm config set @microsoft:registry https://npm.pkg.github.com
          npm config set @vscode:registry https://npm.pkg.github.com
          # Increase network timeout to handle slow connections
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        run: |
          npm run buildreact
          npm run gulp vscode-linux-arm64-min
      - name: Package
        run: |
          mkdir -p .build/linux/client
          ARCHIVE_PATH=".build/linux/client/void-linux-arm64.tar.gz"
          tar -czf $ARCHIVE_PATH -C .. VSCode-linux-arm64
      - name: Generate checksum
        run: |
          cd .build/linux/client
          sha256sum void-linux-arm64.tar.gz > void-linux-arm64.tar.gz.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: void-linux-arm64
          path: |
            .build/linux/client/void-linux-arm64.tar.gz
            .build/linux/client/void-linux-arm64.tar.gz.sha256
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Set npm config to use GitHub token for authentication to avoid rate limits
          npm config set //github.com/:_authToken=${{ github.token }}
          npm config set //api.github.com/:_authToken=${{ github.token }}
          npm config set //npm.pkg.github.com/:_authToken=${{ github.token }}
          # Configure npm to use the GitHub token for all requests to github.com domains
          npm config set @microsoft:registry https://npm.pkg.github.com
          npm config set @vscode:registry https://npm.pkg.github.com
          # Increase network timeout to handle slow connections
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        run: |
          npm run buildreact
          npm run gulp vscode-win32-x64-min
      - name: Package
        run: |
          mkdir -p .build/win32-x64
          Compress-Archive -Path ..\VSCode-win32-x64\* -DestinationPath .build\win32-x64\devforge-win32-x64.zip
        shell: pwsh

      - name: Generate checksum
        run: |
          cd .build/win32-x64
          $hash = Get-FileHash -Algorithm SHA256 devforge-win32-x64.zip
          $hash.Hash | Out-File -Encoding ascii devforge-win32-x64.zip.sha256
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: void-win32-x64
          path: |
            .build/win32-x64/dwvforge-win32-x64.zip
            .build/win32-x64/devforge-win32-x64.zip.sha256
  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Set npm config to use GitHub token for authentication to avoid rate limits
          npm config set //github.com/:_authToken=${{ github.token }}
          npm config set //api.github.com/:_authToken=${{ github.token }}
          npm config set //npm.pkg.github.com/:_authToken=${{ github.token }}
          # Configure npm to use the GitHub token for all requests to github.com domains
          npm config set @microsoft:registry https://npm.pkg.github.com
          npm config set @vscode:registry https://npm.pkg.github.com
          # Increase network timeout to handle slow connections
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        run: |
          npm run buildreact
          npm run gulp vscode-win32-arm64-min
      - name: Package
        run: |
          mkdir -p .build/win32-arm64
          Compress-Archive -Path ..\VSCode-win32-arm64\* -DestinationPath .build\win32-arm64\devforge-win32-arm64.zip
        shell: pwsh

      - name: Generate checksum
        run: |
          cd .build/win32-arm64
          $hash = Get-FileHash -Algorithm SHA256 devforge-win32-arm64.zip
          $hash.Hash | Out-File -Encoding ascii devforge-win32-arm64.zip.sha256
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: void-win32-arm64
          path: |
            .build/win32-arm64/devforge-win32-arm64.zip
            .build/win32-arm64/dwvforge-win32-arm64.zip.sha256
